version: '3'

services:
  app:
    build: .
    working_dir: /usr/src/transmission-helper
    stdin_open: true
    tty: true
    depends_on:
      - mailhog
    environment:
      TH_CONFIG_PATH: "/usr/src/transmission-helper/config.yaml"
    volumes:
      - .:/usr/src/transmission-helper

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    environment:
      MH_AUTH_FILE: /opt/mailhog_auth_file.txt
    volumes:
      # mailhog_user
      # mailhog_pass
      - ./mailhog_auth_file.txt:/opt/mailhog_auth_file.txt
