name: Test
on: [push]

jobs:
  test:
    name: Build docker image and run test suite
    runs-on: ubuntu-latest
    # env:
    #   COMPOSE_FILE: .ci/docker-compose.yml
    #   DOCKER_USER: ${{ secrets.DOCKER_USER }}
    #   DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose build

    - name: Run tests
      run: docker-compose run app sh -c 'go test -v'
